---
title: "chinacode"
author: "Sherry Hu"
date: "5/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(mice)
library(reshape2)
library(ggplot2)
library(lme4)
library(lattice)
library(caret)
# read in data
require(haven)
sashhinc=read_sas("hhinc_10.sas7bdat")

```

```{r}
sashhinc[is.na(sashhinc)] = 0
df = select(sashhinc,
            hhid,
            WAVE,
            hhinc_cpi, 
            hhincpc_cpi, 
            HHBUS, 
            HHBUSimp, 
            HHFARM, 
            HHFARMimp, 
            HHFISH, 
            HHFISHimp, 
            hhgard, 
            HHGARDimp,
            HHLVST,
            HHLVSTimp,
            hhNRwage,
            HHNRWAGEimp,
            HHOTHR,
            HHOTHRimp,
            HHRETIRE,
            HHRETIREimp,
            HHSUB,
            HHSUBimp,
            t1,
            urban)

names(df)<- toupper(names(df))
df$T1 = as.factor(df$T1)
head(df)
```

# exploring log transform / outlier removal

## log shift without outlier removal
```{r}
colnames(sashhinc)
summary(sashhinc)
```


```{r}
df$cyear=df$WAVE-1989
df$thousands=df$HHINC_CPI/1000

m2=lmer(thousands ~ cyear + URBAN + T1 + 
          cyear*URBAN + cyear*T1 + URBAN*T1
        + cyear*URBAN*T1 + (1|HHID), data=df)
summary(m2)
anova(m2)

```

```{r}
library(lattice)
qqmath(resid(m2))
plot(m2,resid(.,scaled=TRUE)~fitted(.),abline=0)
```

```{r}
colnames(df)
```

```{r}
df$cyear=df$WAVE-1989
df$thousands=df$HHINC_CPI/1000

m2=lmer(HHINC_CPI ~  HHBUS + HHFARM + HHFISH + HHGARD + HHLVST + HHNRWAGE + HHOTHR  + HHRETIRE + HHSUB + 
          (1|HHID), data=df)
summary(m2)
anova(m2)

```
```{r}
qqmath(resid(m2))
plot(m2,resid(.,scaled=TRUE)~fitted(.),abline=0)
```


# stratified cross validation

```{r}
# get all HHIDs from 1989, sorted by HHINC_CPI
df_1989 = subset(df, WAVE==1989)
length(unique(df_1989$HHID))
df_1989 = df_1989[order(df_1989$HHINC_CPI),]


'%!in%' <- function(x,y)!('%in%'(x,y))

# check if there are any HHID's in 2015 that didn't respond in 1989
sum(unique(subset(df, WAVE=2015)$HHID) %!in% unique(subset(df, WAVE=1989)$HHID))
# check if there are any HHID's in 1989 that weren't in 2015
sum(unique(subset(df, WAVE=1989)$HHID) %!in% unique(subset(df, WAVE=2015)$HHID))


n_folds = 10
MSEs = c()
for(i in 1:n_folds){
  # split into train and test folds
  test_indices = seq(i, nrow(df_1989), n_folds)
  train_fold_HHIDs = df_1989[-test_indices,]$HHID
  test_fold_HHIDs = df_1989[test_indices,]$HHID
  
  train_fold = df[df$HHID %in% train_fold_HHIDs,]
  test_fold = df[df$HHID %in% test_fold_HHIDs,]
  
  #create a new model on train_fold
  our_model = lmer(HHINC_CPI ~  cyear + URBAN + T1 + 
          cyear*URBAN + cyear*T1 + URBAN*T1
        + cyear*URBAN*T1 +
          (1|HHID), data=train_fold)
  
  predictions = predict(our_model, test_fold, allow.new.levels=TRUE)
  residuals = (predictions) - (test_fold$HHINC_CPI)
  MSE = mean(residuals^2)
  MSEs = c(MSEs, MSE)
}
```

```{r}
mean(MSEs)
```


# old stuff

```{r}
sashhinc$cyear=sashhinc$WAVE-1989
sashhinc$thousands=sashhinc$hhinc_cpi/1000

hist(sashhinc$thousands)
```

```{r}
sashhinc$thousands_shifted=sashhinc$thousands - (min(sashhinc$thousands)-0.01)
hist(log(sashhinc$thousands_shifted))
```

```{r}
pairs(log(thousands_shifted)~cyear + urban + t1, data=sashhinc)
```

```{r}

m2=lmer(log(thousands_shifted) ~ cyear + urban + t1 + 
          cyear*urban + cyear*t1 + urban*t1 
        + cyear*urban*t1 + (1|hhid),data=sashhinc, REML=FALSE)
summary(m2)
```

```{r}
# ggplot(sashhinc, aes(x=cyear,y=thousands,group=hhid)) +
#   ylim(-500,1500) + 
#   geom_point(alpha=0.05) + geom_line(alpha=0.1) +
#   geom_abline(data=est, aes(intercept=int, slope=sl),col="red") +
#   xlab("Years Since 1989") + ylab("Income (thousands of yuan)") + 
#   ggtitle("CHNS Household Income by Year")

```



```{r}
library(lattice)
qqmath(resid(m2))
plot(m2,resid(.,scaled=TRUE)~fitted(.),abline=0)

```

## .1% removed
```{r}
lower = quantile(sashhinc$thousands, 0.001)
upper = quantile(sashhinc$thousands, 0.999)
sashhinc_trimmed = subset(sashhinc, lower < thousands & thousands < upper)
dim(sashhinc)[1] - dim(sashhinc_trimmed)[1]
```

```{r}
m2=lmer((thousands) ~ cyear + urban + t1 + 
          cyear*urban + cyear*t1 + urban*t1 
        + cyear*urban*t1 + (1|hhid),data=sashhinc_trimmed, REML=FALSE)
summary(m2)
```


```{r}
qqmath(resid(m2))
plot(m2,resid(.,scaled=TRUE)~fitted(.),abline=0)

```



```{r}
sashhinc_trimmed$thousands_shifted = sashhinc_trimmed$thousands - (min(sashhinc_trimmed$thousands)-0.01)
m2=lmer(log(thousands_shifted) ~ cyear + urban + t1 + 
          cyear*urban + cyear*t1 + urban*t1 
        + cyear*urban*t1 + (1|hhid),data=sashhinc_trimmed, REML=FALSE)
summary(m2)
```


```{r}
qqmath(resid(m2))
plot(m2,resid(.,scaled=TRUE)~fitted(.),abline=0)
```

## .05% removed

```{r}
lower = quantile(sashhinc$thousands, 0.005)
upper = quantile(sashhinc$thousands, 0.995)
sashhinc_trimmed = subset(sashhinc, lower < thousands & thousands < upper)
dim(sashhinc)[1] - dim(sashhinc_trimmed)[1]
```

```{r}
m2=lmer((thousands) ~ cyear + urban + t1 + 
          cyear*urban + cyear*t1 + urban*t1 
        + cyear*urban*t1 + (1|hhid),data=sashhinc_trimmed, REML=FALSE)
summary(m2)
```


```{r}
qqmath(resid(m2))
plot(m2,resid(.,scaled=TRUE)~fitted(.),abline=0)

```



```{r}
sashhinc_trimmed$thousands_shifted = sashhinc_trimmed$thousands - (min(sashhinc_trimmed$thousands)-0.01)
m2=lmer(log(thousands_shifted) ~ cyear + urban + t1 + 
          cyear*urban + cyear*t1 + urban*t1 
        + cyear*urban*t1 + (1|hhid),data=sashhinc_trimmed)
summary(m2)
```


```{r}
qqmath(resid(m2))
plot(m2,resid(.,scaled=TRUE)~fitted(.),abline=0)
```