---
title: "fixes"
author: "Daniel Zhou"
date: "6/5/2020"
output: html_document
---

```{r}
# libraries that need to be installed and loaded
library(tidyverse)
library(mice)
library(reshape2)
library(ggplot2)
library(lme4)
library(lattice)
library(caret)
library(monomvn)
library(ineq)
library(car)
library(knitr)
library(reshape)
library(lmerTest)
```

```{r}
# read in data
require(haven)
sashhinc=read_sas("hhinc_10.sas7bdat")

# let's make this more interpretable by letting 1989 be year 0
# also let's convert income to thousands of yuan
sashhinc$cyear=sashhinc$WAVE-1989
sashhinc$thousands=sashhinc$hhincpc_cpi/1000
sashhinc = sashhinc[!is.na(sashhinc$hhincpc_cpi), ]

# replace NAs w/ null
sashhinc[is.na(sashhinc)] = 0
sashhinc_trimmed = sashhinc
# shift variables to positive in the case we want to use a log transform 
sashhinc$thousands_shifted=sashhinc$thousands - (min(sashhinc$thousands)-1)
sashhinc$log_thousands_shifted = log(sashhinc$thousands_shifted)


# change to categorical variables
sashhinc$urban <- as.factor(sashhinc$urban)
sashhinc$hhid <- as.factor(sashhinc$hhid)
sashhinc$t1 <- as.factor(sashhinc$t1)

# refactor t1
sashhinc$t1 <- factor(sashhinc$t1, levels = c("21", "11", "23", "31", "32", "37", "41", "42", "43", "45", "52", "55"))

```


```{r data_cleaning}
# select variables we need for df
df = dplyr::select(sashhinc,
            hhid,
            WAVE,
            hhinc_cpi, 
            hhincpc_cpi, 
            HHBUS, 
            HHBUSimp, 
            HHFARM, 
            HHFARMimp, 
            HHFISH, 
            HHFISHimp, 
            hhgard, 
            HHGARDimp,
            HHLVST,
            HHLVSTimp,
            hhNRwage,
            HHNRWAGEimp,
            HHOTHR,
            HHOTHRimp,
            HHRETIRE,
            HHRETIREimp,
            HHSUB,
            HHSUBimp,
            t1,
            urban,
            thousands,
            cyear,
            thousands_shifted,
            log_thousands_shifted)

names(df)<- toupper(names(df))

df = df[!is.na(df$HHINCPC_CPI), ]

#add primary income source variable
df <- df %>% 
        mutate(Primary = colnames(df[, c("HHBUS", "HHFARM", "HHFISH", "HHGARD", "HHLVST", "HHOTHR", "HHRETIRE", "HHSUB")])[apply(df[, c("HHBUS", "HHFARM", "HHFISH", "HHGARD", "HHLVST", "HHOTHR", "HHRETIRE", "HHSUB")], 1, which.max)])

#add variable indicating whether household receives income from specific sources
df <- df %>% 
  mutate(business_ind = factor(as.numeric(HHBUS != 0)),
         farm_ind = factor(as.numeric(HHFARM != 0)),
         fish_ind = factor(as.numeric(HHFISH != 0)),
         gard_ind = factor(as.numeric(HHGARD != 0)),
         lvst_ind = factor(as.numeric(HHLVST != 0)),
         othr_ind = factor(as.numeric(HHOTHR != 0)),
         retire_ind = factor(as.numeric(HHRETIRE != 0)),
         sub_ind = factor(as.numeric(HHSUB != 0)))

df <- df %>% 
  mutate(T1_11_ind = factor(T1 == 11),
         T1_21_ind = factor(T1 == 21),
         T1_23_ind = factor(T1 == 23),
         T1_31_ind = factor(T1 == 31),
         T1_32_ind = factor(T1 == 32),
         T1_37_ind = factor(T1 == 37),
         T1_41_ind = factor(T1 == 41),
         T1_42_ind = factor(T1 == 42),
         T1_43_ind = factor(T1 == 43),
         T1_45_ind = factor(T1 == 45),
         T1_52_ind = factor(T1 == 52),
         T1_55_ind = factor(T1 == 55))

# make T/F -> 1/0
df$T1_11_ind <- as.factor(as.integer(as.logical(df$T1_11_ind)))
df$T1_21_ind <- as.factor(as.integer(as.logical(df$T1_21_ind)))
df$T1_23_ind <- as.factor(as.integer(as.logical(df$T1_23_ind)))
df$T1_31_ind <- as.factor(as.integer(as.logical(df$T1_31_ind)))
df$T1_32_ind <- as.factor(as.integer(as.logical(df$T1_32_ind)))
df$T1_37_ind <- as.factor(as.integer(as.logical(df$T1_37_ind)))
df$T1_41_ind <- as.factor(as.integer(as.logical(df$T1_41_ind)))
df$T1_42_ind <- as.factor(as.integer(as.logical(df$T1_42_ind)))
df$T1_43_ind <- as.factor(as.integer(as.logical(df$T1_43_ind)))
df$T1_45_ind <- as.factor(as.integer(as.logical(df$T1_45_ind)))
df$T1_52_ind <- as.factor(as.integer(as.logical(df$T1_52_ind)))
df$T1_55_ind <- as.factor(as.integer(as.logical(df$T1_55_ind)))

names(df)<- toupper(names(df))
df$T1 = as.factor(df$T1)


head(df)

lower = quantile(df$THOUSANDS, 0.001)
upper = quantile(df$THOUSANDS, 0.999)
df_trimmed = subset(df, lower < THOUSANDS & THOUSANDS < upper)

## .1% removed (negative outliers) - put in trimmed df
lower = quantile(df$THOUSANDS, 0.001)
df_trimmed = subset(df, lower < THOUSANDS)
df_trimmed$THOUSANDS_SHIFTED =df_trimmed$THOUSANDS - (min(df_trimmed$THOUSANDS)-1)
df_trimmed$LOG_THOUSANDS_SHIFTED = log(df_trimmed$THOUSANDS_SHIFTED)

# shift df variables by min as well
df$THOUSANDS_SHIFTED =df$THOUSANDS - (min(df$THOUSANDS)-1)
df$LOG_THOUSANDS_SHIFTED = log(df$THOUSANDS_SHIFTED)
```


# split into train test 
```{r}
# train test fold using full dataset
HHIDs = unique(df$HHID)
set.seed(0)
HHIDs = sample(HHIDs)
# split into train and test folds
test_indices = seq(1, length(HHIDs), 5)
train_fold_HHIDs = HHIDs[-test_indices]
test_fold_HHIDs = HHIDs[test_indices]

train_fold = df[df$HHID %in% train_fold_HHIDs,]
test_fold = df[df$HHID %in% test_fold_HHIDs,]

model_score = function(model, model_name){
  predictions = predict(model, test_fold, allow.new.levels=TRUE)
  residuals = exp((predictions)) - exp((test_fold$LOG_THOUSANDS_SHIFTED))
  MSE = mean(residuals^2)
  cat("full dataset", model_name, "MSE", MSE)
}

# train test fold using trimmed dataset
HHIDs = unique(df_trimmed$HHID)
set.seed(0)
HHIDs = sample(HHIDs)
# split into train and test folds
test_indices = seq(1, length(HHIDs), 5)
train_fold_HHIDs = HHIDs[-test_indices]
test_fold_HHIDs = HHIDs[test_indices]

trimmed_train_fold = df_trimmed[df_trimmed$HHID %in% train_fold_HHIDs,]
trimmed_test_fold = df_trimmed[df_trimmed$HHID %in% test_fold_HHIDs,]

model_score_trimmed = function(model, model_name){
  predictions = predict(model, trimmed_test_fold, allow.new.levels=TRUE)
  residuals = exp((predictions)) - exp((trimmed_test_fold$LOG_THOUSANDS_SHIFTED))
  MSE = mean(residuals^2)
  cat("trimmed dataset", model_name, "MSE", MSE)
}

```


```{r}
# initial model
# considers main effects and 2-way interactions with CYEAR in it
# random effect for household 
# gardening is the baseline for income source
m1 = lmer(LOG_THOUSANDS_SHIFTED ~ CYEAR + T1 +  URBAN + BUSINESS_IND + FARM_IND + FISH_IND +  LVST_IND + OTHR_IND + RETIRE_IND + SUB_IND + CYEAR*URBAN + #T1_21_IND*CYEAR +#
T1_23_IND*CYEAR + T1_32_IND*CYEAR + T1_41_IND*CYEAR + T1_42_IND*CYEAR + T1_43_IND*CYEAR + T1_45_IND*CYEAR + T1_52_IND*CYEAR + CYEAR * BUSINESS_IND + CYEAR * FARM_IND + CYEAR * FISH_IND +
CYEAR * LVST_IND + CYEAR * OTHR_IND + CYEAR * RETIRE_IND + CYEAR * SUB_IND + (1|HHID), data = trimmed_train_fold)

summary(m1)
```

```{r}
model_score_trimmed(m1, "m1")
qqmath(resid(m1))
plot(m1,resid(.,scaled=TRUE)~fitted(.),abline=0, xlab = "Fitted Values", ylab = "Residuals")
```

# Model Selection
```{r}
# m2 = lmer(LOG_THOUSANDS_SHIFTED ~ CYEAR + T1 +  URBAN + BUSINESS_IND + FARM_IND + FISH_IND + GARD_IND + LVST_IND + OTHR_IND + RETIRE_IND + SUB_IND + (1 | HHID),data=df_trimmed, REML = FALSE)

variables_of_interest = c("CYEAR * URBAN", 
                         # "T1_21_IND*CYEAR", # Liaoning Baseline
                         # "T1_11_IND*CYEAR", 
                         "T1_23_IND*CYEAR", 
                        # "T1_31_IND*CYEAR", 
                         "T1_32_IND*CYEAR",
                         "T1_37_IND*CYEAR",
                         "T1_41_IND*CYEAR",
                         "T1_42_IND*CYEAR",
                         "T1_43_IND*CYEAR",
                         "T1_45_IND*CYEAR",
                         "T1_52_IND*CYEAR",
                        # "T1_55_IND*CYEAR",
                          "CYEAR * BUSINESS_IND",
                          "CYEAR * FARM_IND", 
                          "CYEAR * FISH_IND",
                         # "CYEAR * GARD_IND",
                          "CYEAR * LVST_IND",
                          "CYEAR * OTHR_IND", 
                          "CYEAR * RETIRE_IND",
                          "CYEAR * SUB_IND")

remaining_variables_of_interest = variables_of_interest

current_variables = c("CYEAR",
                      "URBAN",
                      "T1",
                      "BUSINESS_IND",
                      "FARM_IND", 
                      "FISH_IND",
                      # "GARD_IND",
                      "LVST_IND",
                      "OTHR_IND", 
                      "RETIRE_IND",
                      "SUB_IND",
                      "(1|HHID)")
current_formula = as.formula(paste("LOG_THOUSANDS_SHIFTED ~ ",paste(current_variables, collapse="+"),sep = ""))

while(TRUE){
  print("current baseline")
  print(current_variables)
  # get baseline
  current_formula = as.formula(paste("LOG_THOUSANDS_SHIFTED ~ ",paste(current_variables, collapse="+"),sep = ""))
  baseline = lmer(current_formula, data=df_trimmed, REML=FALSE)
  
  # loop through remaining variables of interest and create a new model
  models = c()
  for (var in remaining_variables_of_interest){
    curr_var_loop = c(current_variables, var)
    current_formula = as.formula(paste("LOG_THOUSANDS_SHIFTED~ ",paste(curr_var_loop, collapse="+"),sep = ""))
    new_model = lmer(current_formula, data=df_trimmed, REML=FALSE)
    models = c(models, new_model)
  }
  
  # perform anova on baseline and a new model, record the resulting p-value
  p_vals = c()
  for (m in models){
    anova_result = anova(baseline, m)
    p_vals= c(p_vals, anova_result$`Pr(>Chisq)`[2])
  }
  
  # if the smallest p-value is greater than 0.05, stop because no new variable is significant
  if (min(p_vals)>0.05){
    print("no remaining significant variables of interest")
    break
  }
  print(paste("selected", remaining_variables_of_interest[which.min(p_vals)], ", p-value of", min(p_vals) ))
  
  # add most signficant variable to model
  current_variables = c(current_variables, remaining_variables_of_interest[which.min(p_vals)])
  
  # remove the most significant variable from search space
  remaining_variables_of_interest = remaining_variables_of_interest[-which.min(p_vals)]
  if (length(remaining_variables_of_interest)==0){
    break
  }
}
```

```{r}
selected_model = as.formula(paste("LOG_THOUSANDS_SHIFTED ~ ",paste(current_variables, collapse="+"),sep = ""))
selected_model
```

# Checking our model selection with lmer: step 
```{r}
library(lmerTest)
m3 = lmer(LOG_THOUSANDS_SHIFTED ~ CYEAR +
            T1 +
            URBAN +
            BUSINESS_IND +
            FARM_IND +
            FISH_IND +
            # GARD_IND + baseline
            LVST_IND +
            OTHR_IND +
            RETIRE_IND +
            SUB_IND +
            (1 | HHID) +
            CYEAR * URBAN +
            # T1_21_IND*CYEAR+ Lianoning- baseline 
		        # T1_11_IND*CYEAR+ Beijing
             T1_23_IND*CYEAR+
            #T1_31_IND*CYEAR+ Shanghai
             T1_32_IND*CYEAR+
             T1_37_IND*CYEAR+
             T1_41_IND*CYEAR+
             T1_42_IND*CYEAR+
             T1_43_IND*CYEAR+
             T1_45_IND*CYEAR+
             T1_52_IND*CYEAR+
            # T1_55_IND*CYEAR+ Chongqing
            CYEAR * BUSINESS_IND +
            CYEAR * FARM_IND +
            CYEAR * FISH_IND +
           # CYEAR * GARD_IND + baseline
            CYEAR * LVST_IND +
            CYEAR * OTHR_IND +
            CYEAR * RETIRE_IND +
            CYEAR * SUB_IND,data=df_trimmed, REML = FALSE)
lmerTest::step(m3,reduce.fixed = FALSE)
```

```{r}
step_model = lmer(LOG_THOUSANDS_SHIFTED ~ CYEAR + T1 + URBAN + BUSINESS_IND + FARM_IND + 
    FISH_IND + LVST_IND + OTHR_IND + RETIRE_IND + SUB_IND + (1 | 
    HHID) + CYEAR * URBAN + T1_23_IND * CYEAR + T1_32_IND * CYEAR + 
    T1_37_IND * CYEAR + T1_41_IND * CYEAR + T1_42_IND * CYEAR + 
    T1_43_IND * CYEAR + T1_45_IND * CYEAR + T1_52_IND * CYEAR + 
    CYEAR * BUSINESS_IND + CYEAR * FARM_IND + CYEAR * FISH_IND + 
    CYEAR * LVST_IND + CYEAR * OTHR_IND + CYEAR * RETIRE_IND + 
    CYEAR * SUB_IND, data=df_trimmed)
vif(step_model)
```

# FINAL MODEL HERE 
```{r}
options(digits=4, scipen=5)

# this is with liaoning as baseline for interactions
model_final = lmer(LOG_THOUSANDS_SHIFTED ~ CYEAR + URBAN + T1 + BUSINESS_IND + FARM_IND + 
    FISH_IND + LVST_IND + OTHR_IND + RETIRE_IND + SUB_IND + (1 | 
    HHID) + CYEAR * RETIRE_IND + T1_23_IND * CYEAR + T1_32_IND * 
    CYEAR + CYEAR * BUSINESS_IND + T1_45_IND * CYEAR + T1_41_IND * 
    CYEAR + T1_43_IND * CYEAR + T1_37_IND * CYEAR + CYEAR * URBAN + 
    CYEAR * SUB_IND + T1_52_IND * CYEAR + T1_42_IND * CYEAR + 
    CYEAR * LVST_IND + CYEAR * OTHR_IND, data=df_trimmed)

summary(model_final)
model_score_trimmed(model_final, "model_final")
```

```{r}
qqmath(resid(model_final))
plot(model_final,resid(.,scaled=TRUE)~fitted(.),abline=0, xlab = "Fitted Values", ylab = "Residuals")
hist(df_trimmed$LOG_THOUSANDS_SHIFTED)
```

```{r}
vif(model_final)
```

```{r}
CI_interval = confint(model_final)
exp_CI_interval = exp(CI_interval)
```

```{r}
# model fit on data w/ negative outliers
model_outliers = lmer(LOG_THOUSANDS_SHIFTED ~ CYEAR + URBAN + T1 + BUSINESS_IND + FARM_IND + 
    FISH_IND + LVST_IND + OTHR_IND + RETIRE_IND + SUB_IND + (1 | 
    HHID) + CYEAR * RETIRE_IND + T1_23_IND * CYEAR + T1_32_IND * 
    CYEAR + CYEAR * BUSINESS_IND + T1_45_IND * CYEAR + T1_41_IND * 
    CYEAR + T1_43_IND * CYEAR + T1_37_IND * CYEAR + CYEAR * URBAN + 
    CYEAR * SUB_IND + T1_52_IND * CYEAR + T1_42_IND * CYEAR + 
    CYEAR * LVST_IND + CYEAR * OTHR_IND, data=df)
summary(model_outliers)  
```

# 3 way interaction

```{r}
# this will take too long to run
# 
variables_of_interest = c("CYEAR * URBAN * T1",
"CYEAR * URBAN * BUSINESS_IND",
"CYEAR * URBAN * FARM_IND",
"CYEAR * URBAN * FISH_IND",
"CYEAR * URBAN * LVST_IND",
"CYEAR * URBAN * OTHR_IND",
"CYEAR * URBAN * RETIRE_IND",
"CYEAR * URBAN * SUB_IND",
"CYEAR * T1 * BUSINESS_IND",
"CYEAR * T1 * FARM_IND",
"CYEAR * T1 * FISH_IND",
"CYEAR * T1 * LVST_IND",
"CYEAR * T1 * OTHR_IND",
"CYEAR * T1 * RETIRE_IND",
"CYEAR * T1 * SUB_IND",
"CYEAR * BUSINESS_IND * FARM_IND",
"CYEAR * BUSINESS_IND * FISH_IND",
"CYEAR * BUSINESS_IND * LVST_IND",
"CYEAR * BUSINESS_IND * OTHR_IND",
"CYEAR * BUSINESS_IND * RETIRE_IND",
"CYEAR * BUSINESS_IND * SUB_IND",
"CYEAR * FARM_IND * FISH_IND",
"CYEAR * FARM_IND * LVST_IND",
"CYEAR * FARM_IND * OTHR_IND",
"CYEAR * FARM_IND * RETIRE_IND",
"CYEAR * FARM_IND * SUB_IND",
"CYEAR * FISH_IND * LVST_IND",
"CYEAR * FISH_IND * OTHR_IND",
"CYEAR * FISH_IND * RETIRE_IND",
"CYEAR * FISH_IND * SUB_IND",
"CYEAR * LVST_IND * OTHR_IND",
"CYEAR * LVST_IND * RETIRE_IND",
"CYEAR * LVST_IND * SUB_IND",
"CYEAR * OTHR_IND * RETIRE_IND",
"CYEAR * OTHR_IND * SUB_IND",
"CYEAR * RETIRE_IND * SUB_IND",
"URBAN * T1 * BUSINESS_IND" #,
# "URBAN * T1 * FARM_IND",
# "URBAN * T1 * FISH_IND",
# "URBAN * T1 * LVST_IND",
# "URBAN * T1 * OTHR_IND",
# "URBAN * T1 * RETIRE_IND",
# "URBAN * T1 * SUB_IND",
# "URBAN * BUSINESS_IND * FARM_IND",
# "URBAN * BUSINESS_IND * FISH_IND",
# "URBAN * BUSINESS_IND * LVST_IND",
# "URBAN * BUSINESS_IND * OTHR_IND",
# "URBAN * BUSINESS_IND * RETIRE_IND",
# "URBAN * BUSINESS_IND * SUB_IND",
# "URBAN * FARM_IND * FISH_IND",
# "URBAN * FARM_IND * LVST_IND",
# "URBAN * FARM_IND * OTHR_IND",
# "URBAN * FARM_IND * RETIRE_IND",
# "URBAN * FARM_IND * SUB_IND",
# "URBAN * FISH_IND * LVST_IND",
# "URBAN * FISH_IND * OTHR_IND",
# "URBAN * FISH_IND * RETIRE_IND",
# "URBAN * FISH_IND * SUB_IND",
# "URBAN * LVST_IND * OTHR_IND",
# "URBAN * LVST_IND * RETIRE_IND",
# "URBAN * LVST_IND * SUB_IND",
# "URBAN * OTHR_IND * RETIRE_IND",
# "URBAN * OTHR_IND * SUB_IND",
# "URBAN * RETIRE_IND * SUB_IND",
# "T1 * BUSINESS_IND * FARM_IND",
# "T1 * BUSINESS_IND * FISH_IND",
# "T1 * BUSINESS_IND * LVST_IND",
# "T1 * BUSINESS_IND * OTHR_IND",
# "T1 * BUSINESS_IND * RETIRE_IND",
# "T1 * BUSINESS_IND * SUB_IND",
# "T1 * FARM_IND * FISH_IND",
# "T1 * FARM_IND * LVST_IND",
# "T1 * FARM_IND * OTHR_IND",
# "T1 * FARM_IND * RETIRE_IND",
# "T1 * FARM_IND * SUB_IND",
# "T1 * FISH_IND * LVST_IND",
# "T1 * FISH_IND * OTHR_IND",
# "T1 * FISH_IND * RETIRE_IND",
# "T1 * FISH_IND * SUB_IND",
# "T1 * LVST_IND * OTHR_IND",
# "T1 * LVST_IND * RETIRE_IND",
# "T1 * LVST_IND * SUB_IND",
# "T1 * OTHR_IND * RETIRE_IND",
# "T1 * OTHR_IND * SUB_IND",
# "T1 * RETIRE_IND * SUB_IND",
# "BUSINESS_IND * FARM_IND * FISH_IND",
# "BUSINESS_IND * FARM_IND * LVST_IND",
# "BUSINESS_IND * FARM_IND * OTHR_IND",
# "BUSINESS_IND * FARM_IND * RETIRE_IND",
# "BUSINESS_IND * FARM_IND * SUB_IND",
# "BUSINESS_IND * FISH_IND * LVST_IND",
# "BUSINESS_IND * FISH_IND * OTHR_IND",
# "BUSINESS_IND * FISH_IND * RETIRE_IND",
# "BUSINESS_IND * FISH_IND * SUB_IND",
# "BUSINESS_IND * LVST_IND * OTHR_IND",
# "BUSINESS_IND * LVST_IND * RETIRE_IND",
# "BUSINESS_IND * LVST_IND * SUB_IND",
# "BUSINESS_IND * OTHR_IND * RETIRE_IND",
# "BUSINESS_IND * OTHR_IND * SUB_IND",
# "BUSINESS_IND * RETIRE_IND * SUB_IND",
# "FARM_IND * FISH_IND * LVST_IND",
# "FARM_IND * FISH_IND * OTHR_IND",
# "FARM_IND * FISH_IND * RETIRE_IND",
# "FARM_IND * FISH_IND * SUB_IND",
# "FARM_IND * LVST_IND * OTHR_IND",
# "FARM_IND * LVST_IND * RETIRE_IND",
# "FARM_IND * LVST_IND * SUB_IND",
# "FARM_IND * OTHR_IND * RETIRE_IND",
# "FARM_IND * OTHR_IND * SUB_IND",
# "FARM_IND * RETIRE_IND * SUB_IND",
# "FISH_IND * LVST_IND * OTHR_IND",
# "FISH_IND * LVST_IND * RETIRE_IND",
# "FISH_IND * LVST_IND * SUB_IND",
# "FISH_IND * OTHR_IND * RETIRE_IND",
# "FISH_IND * OTHR_IND * SUB_IND",
# "FISH_IND * RETIRE_IND * SUB_IND",
# "LVST_IND * OTHR_IND * RETIRE_IND",
# "LVST_IND * OTHR_IND * SUB_IND",
# "LVST_IND * RETIRE_IND * SUB_IND",
# "OTHR_IND * RETIRE_IND * SUB_IND"
)

remaining_variables_of_interest = variables_of_interest

current_variables = c("URBAN",
"T1",
"BUSINESS_IND",
"FARM_IND",
"FISH_IND",
"LVST_IND",
"OTHR_IND",
"RETIRE_IND",
"SUB_IND",
"(1 | HHID)",
"CYEAR * RETIRE_IND",
"T1_23_IND * CYEAR",
"T1_32_IND * CYEAR",
"CYEAR * BUSINESS_IND",
"T1_45_IND * CYEAR",
"T1_41_IND * CYEAR",
"T1_43_IND * CYEAR",
"T1_37_IND * CYEAR",
"CYEAR * URBAN",
"CYEAR * SUB_IND",
"T1_52_IND * CYEAR",
"T1_42_IND * CYEAR",
"CYEAR * LVST_IND",
"CYEAR * OTHR_IND")
current_formula = as.formula(paste("LOG_THOUSANDS_SHIFTED ~ ",paste(current_variables, collapse="+"),sep = ""))

while(TRUE){
  print("current baseline")
  print(current_variables)
  # get baseline
  current_formula = as.formula(paste("LOG_THOUSANDS_SHIFTED ~ ",paste(current_variables, collapse="+"),sep = ""))
  baseline = lmer(current_formula, data=df_trimmed, REML=FALSE)

  # loop through remaining variables of interest and create a new model
  models = c()
  for (var in remaining_variables_of_interest){
    curr_var_loop = c(current_variables, var)
    current_formula = as.formula(paste("LOG_THOUSANDS_SHIFTED~ ",paste(curr_var_loop, collapse="+"),sep = ""))
    new_model = lmer(current_formula, data=df_trimmed, REML=FALSE)
    models = c(models, new_model)
  }

  # perform anova on baseline and a new model, record the resulting p-value
  p_vals = c()
  for (m in models){
    anova_result = anova(baseline, m)
    p_vals= c(p_vals, anova_result$`Pr(>Chisq)`[2])
  }

  # if the smallest p-value is greater than 0.05, stop because no new variable is significant
  if (min(p_vals)>0.05){
    print("no remaining significant variables of interest")
    break
  }
  print(paste("selected", remaining_variables_of_interest[which.min(p_vals)], ", p-value of", min(p_vals) ))

  # add most signficant variable to model
  current_variables = c(current_variables, remaining_variables_of_interest[which.min(p_vals)])

  # remove the most significant variable from search space
  remaining_variables_of_interest = remaining_variables_of_interest[-which.min(p_vals)]
  if (length(remaining_variables_of_interest)==0){
    break
  }
}
```

# Model with Outliers
```{r}
model_outliers = lmer(LOG_THOUSANDS_SHIFTED ~ CYEAR + URBAN + T1 + BUSINESS_IND + FARM_IND + 
    FISH_IND + LVST_IND + OTHR_IND + RETIRE_IND + SUB_IND + (1 | 
    HHID) + CYEAR * RETIRE_IND + T1_23_IND * CYEAR + T1_32_IND * 
    CYEAR + CYEAR * BUSINESS_IND + T1_45_IND * CYEAR + T1_41_IND * 
    CYEAR + T1_43_IND * CYEAR + T1_37_IND * CYEAR + CYEAR * URBAN + 
    CYEAR * SUB_IND + T1_52_IND * CYEAR + T1_42_IND * CYEAR + 
    CYEAR * LVST_IND + CYEAR * OTHR_IND, data=df)
```

```{r}
final.coef = coef(summary(model_final))[ , "Estimate"]
exp.final.coef = exp(coef(summary(model_final))[ , "Estimate"])
outliers.coef = coef(summary(model_outliers))[ , "Estimate"]
exp.outlier.coef = exp(coef(summary(model_outliers))[ , "Estimate"])

CI_interval.final = confint(model_final)
exp_CI_interval.final = exp(CI_interval.final)
test.final = exp_CI_interval.final[-3,]

CI_interval = confint(model_outliers)
exp_CI_interval = exp(CI_interval)
test.outliers = exp_CI_interval[-3,]
```

```{r}
comparison <- cbind(coef_final = final.coef, coef_outlers = outliers.coef,exp_final_coef = exp.final.coef,exp_outlier_coec = exp.outlier.coef)
knitr::kable(comparison , digits = 4,format = "latex")
```

```{r}
outliers.coef
```

```{r}
print(exp.outlier.coef,digits = 4)
```


